In [1]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [2]:
data= pd.read_csv('../datasets/ads/Advertising.csv')
feature_cols = ["TV", "Radio", "Newspaper"]

In [3]:
X = data[feature_cols]
Y = data["Sales"]

In [4]:
# Haxme un modelo lineal
estimator = SVR(kernel="linear")

# Quiero que tenga 2 variables predictoras
selector = RFE(estimator, 2, step = 1)
selector = selector.fit(X,Y)

# Dime cuáles fueron las variables seleccionadas
selector.support_

array([ True,  True, False])

In [5]:
# Por lo tanto el mejor modelo es Sales~TV+Radio

selector.ranking_

array([1, 1, 2])

In [6]:
# 1 es que es más significativa

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
x_pred = X[["TV", "Radio"]]

In [9]:
x_pred

TV  Radio
0    230.1   37.8
1     44.5   39.3
2     17.2   45.9
3    151.5   41.3
4    180.8   10.8
..     ...    ...
195   38.2    3.7
196   94.2    4.9
197  177.0    9.3
198  283.6   42.0
199  232.1    8.6

[200 rows x 2 columns]

In [10]:
lm = LinearRegression()

In [11]:
lm.fit(x_pred, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
# donde corta el eje Y 
lm.intercept_

2.921099912405138

In [13]:
# coeficientes que acompañan TV y Radio respectivamentel
lm.coef_

array([0.04575482, 0.18799423])

In [14]:
# R2 ajustado:
lm.score(x_pred, Y)

0.8971942610828956